spring:
  application:
    name: blossom_backend
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
  h2:
    console:
      path: "/h2-console"
      enabled: true